spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: add_service_route #http://localhost:7779/add?a=1&b=2
          uri: http://localhost:7777
          predicates:
            - Path=/add/**
        - id: multiply_service_route #http://localhost:7779/add?a=1&b=2
          uri: http://localhost:7778
          predicates:
            - Path=/multiply/**
        - id: add_service_route_rewritten #http://localhost:7779/saberi/?a=1&b=2
          uri: http://localhost:7777
          predicates:
            - Path=/saberi/**
          filters:
            - RewritePath=/saberi/(?<a>[^/]+)/(?<b>[^/]+), /add?a=$\{a}&b=$\{b}
        - id: multiply_service_route_rewritten
          uri: http://localhost:7778
          predicates:
            - Path=/pomnozi/**
          filters:
            - RewritePath=/pomnozi/(?<a>[^/]+)/(?<b>[^/]+), /multiply?a=$\{a}&b=$\{b}

server:
  port: 7779

management:
  endpoints:
    web:
      exposure:
        include: gateway
