spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: add_service_route
        uri: localhost:7777
        predicates:
        - Path=/saberi/{segment},/dodaj/{segment}

server:
  port: 7779

management:
  endpoints:
    web:
      exposure:
        include: gateway
